### ISSUE TITLE
Full disk access check no longer works in Monterey

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [MacPaw/PermissionsKit#18]
It seems Apple is no longer creating a CloudTabs.db file in ~/Library/Safari in Monterey and thus the `_fullDiskAuthorizationStatus` function always says Full Disk Access authorization is not determined. Seems likely they've done away with that in introducing tab groups.

To replicate:

1. Update to macOS Monterey (I tested with 12.4)
2. Create a new user in System Preferences
3. Log in as that user
4. Try to get the Full Disk Access authorization status
It'll always be not determined even when it's granted.

Note Apple didn't delete the file when updating to Monterey - on my regular account it's still there but has not been opened or modified since I installed Monterey. So it works for existing users but of course anyone who buys a new Mac or gets a new account this does not work.

**Comment by serejahh** [comment]
Hi, @jordanhbuiltbyhq 
Thanks for raising the issue. We're working on a fix. Stay tuned 😊

**Comment by jordanhbuiltbyhq** [comment]
Unless yall have a better solution, it seems we could use ~/Library/Application Support/com.apple.TCC/TCC.db instead. Doesn't seem as likely that'd disappear in a future update. 😅 [https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive](https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive)
