### ISSUE TITLE
macOS Catalina 10.15 compatibility

### ISSUE THREAD

**Issue by hipwelljo** [MacPaw/PermissionsKit#3]
First, thank you for sharing this! I am looking to determine if full disk access is enabled in Catalina. Looking into it, Library/Safari does not exist anymore, so the check is always "not determined." 😟 Would loooove to have this updated with Catalina compatibility!

**Comment by Krivoblotsky** [comment]
Hey, @hipwelljo.
Thanks for reporting this. I can confirm the issue. We'll investigate the workaround and get back to you as soon as possible.

**Comment by Krivoblotsky** [comment]
Fixed with https://github.com/MacPaw/PermissionsKit/pull/4
