### ISSUE TITLE
Carthage Build Doesn't Work

### ISSUE THREAD

**Issue by jraymonds86** [MacPaw/PermissionsKit#8]
With a Cartfile of:

github "MacPaw/PermissionsKit"

One gets the following results:

$ carthage update
*** Fetching PermissionsKit
*** Checking out PermissionsKit at "1.0.1"
*** xcodebuild output can be found in ...
*** Skipped building PermissionsKit due to the error:
Dependency "PermissionsKit" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/MacPaw/PermissionsKit/issues/new
$

**Comment by jmiltner** [comment]
I have created pull request #9 that should fix this problem...

**Comment by Krivoblotsky** [comment]
Resolved with 
https://github.com/MacPaw/PermissionsKit/pull/9
